services:

  web:
    container_name: SIGBAS-WEB
    image: node:16.19-buster-slim
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn run dev"
    volumes:
      - ./web:/usr/src/app
    # environment:      
    #   - NEXT_PUBLIC_STRAPI_URL_FRONT=${NEXT_PUBLIC_STRAPI_URL_FRONT}
    #   - STRAPI_URL_BACK=${STRAPI_URL_BACK}
    expose:
      - "3000"
    ports: 
      - 3000:3000
    depends_on: 
      - db
    links:
      - "db:database"

  db:
    container_name: SIGBAS-DB
    image: mariadb:10.7.8-focal
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    expose:
      - "3306"
    ports: 
      - 3306:3306
    volumes:
        - ./datadb:/var/lib/mysql
    #   - ./data_db:/var/lib/mysql

