services:

  web:
    container_name: web
    image: node:lts-slim
    restart: unless-stopped
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn run dev"
    volumes:
      - ./web:/usr/src/app
    environment:      
      - NEXT_PUBLIC_WEB_URL_PUBLIC=${NEXT_PUBLIC_WEB_URL_PUBLIC}
      - WEB_URL_BUILD=${WEB_URL_BUILD}
      - NEXT_PUBLIC_PRISMA_URL_FRONT=${NEXT_PUBLIC_PRISMA_URL_FRONT}
      - PRISMA_URL_BACK=${PRISMA_URL_BACK}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    #   - NEXT_PUBLIC_STRAPI_URL_FRONT=${NEXT_PUBLIC_STRAPI_URL_FRONT}
    #   - STRAPI_URL_BACK=${STRAPI_URL_BACK}
    ports: 
      - "3000:3000"
      - "5555:5555"
    depends_on: 
      - postgres
    networks:
      - sigbas

  postgres:
    container_name: postgres
    image: postgres:15.2-alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./datadb/postgres:/var/lib/postgresql/data
      - ./datadb/dump:/dump
    # expose:
    #   - "5432"
    ports: 
      - "5432:5432"
    networks: 
      - sigbas

networks: 
    sigbas:
        driver: bridge

