import Head from 'next/head'

import LandingContent from 'src/components/landing'


const Home: React.FC = () =>
  <>
    <Head>
      <title>Sistema de Gestión SIGBAS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    <LandingContent />
  </>

export default Home

