import Head from "next/head"

interface Props {
    children: React.ReactNode;
}

const Layout: React.FC<Props> = ({ children }) =>
    <>
        <Head>
            <title>Sistema de Gestión SIGBAS</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />
        </Head>
        <main>
            {children}
        </main>
    </>

export default Layout
